# Generated by Django 3.1.2 on 2021-07-10 20:38

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subbly", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="subblysubscription", name="id",),
        migrations.AddField(
            model_name="subblysubscription",
            name="invite_code",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
