# Generated by Django 3.1.2 on 2021-07-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subbly", "0002_auto_20210710_2038"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subblysubscription",
            constraint=models.UniqueConstraint(
                fields=("subscription_id",), name="unique_subscription"
            ),
        ),
        migrations.AddConstraint(
            model_name="subblysubscription",
            constraint=models.UniqueConstraint(fields=("email",), name="unique_email"),
        ),
    ]
